function template(locals) {
var buf = [];
var jade_mixins = {};
var jade_interp;
;var locals_for_with = (locals || {});(function (my_content) {
var claims = my_content;
{
buf.push("<div class=\"claim-wrapper\"><h4><span class=\"claim-number\">" + (jade.escape((jade_interp = claims[0].number) == null ? '' : jade_interp)) + "</span>Method</h4><p>" + (jade.escape((jade_interp = claims[0].text) == null ? '' : jade_interp)) + "</p><a class=\"expandable\"><span>2</span><span>10</span></a><div id=\"claim1\"><ul><li><span>2</span>" + (jade.escape((jade_interp = claims[1].text) == null ? '' : jade_interp)) + "</li><li><span>3</span>" + (jade.escape((jade_interp = claims[2].text) == null ? '' : jade_interp)) + "</li><li><span>4</span>" + (jade.escape((jade_interp = claims[3].text) == null ? '' : jade_interp)) + "</li><li><span>5</span>" + (jade.escape((jade_interp = claims[4].text) == null ? '' : jade_interp)) + "</li><li><span>6</span>" + (jade.escape((jade_interp = claims[5].text) == null ? '' : jade_interp)) + "</li><li><span>7</span>" + (jade.escape((jade_interp = claims[6].text) == null ? '' : jade_interp)) + "</li><li><span>8</span>" + (jade.escape((jade_interp = claims[7].text) == null ? '' : jade_interp)) + "</li><li><span>9</span>" + (jade.escape((jade_interp = claims[8].text) == null ? '' : jade_interp)) + "</li><li><span>10</span>" + (jade.escape((jade_interp = claims[9].text) == null ? '' : jade_interp)) + "</li></ul></div><!-- /#claim--></div>");
}
buf.push("<!-- /.claim-wrapper--><div class=\"claim-wrapper\"><h4><span class=\"claim-number\">" + (jade.escape((jade_interp = claims[10].number) == null ? '' : jade_interp)) + "</span>Product</h4><p>" + (jade.escape((jade_interp = claims[10].text) == null ? '' : jade_interp)) + "</p><a class=\"expandable\"><span>12</span><span>15</span></a><div id=\"claim2\"><ul><li><span>12</span>" + (jade.escape((jade_interp = claims[11].text) == null ? '' : jade_interp)) + "</li><li><span>13</span>" + (jade.escape((jade_interp = claims[12].text) == null ? '' : jade_interp)) + "</li><li><span>14</span>" + (jade.escape((jade_interp = claims[13].text) == null ? '' : jade_interp)) + "</li><li><span>15</span>" + (jade.escape((jade_interp = claims[14].text) == null ? '' : jade_interp)) + "</li></ul></div><!-- /#claim--></div><!-- /.claim-wrapper--><div class=\"claim-wrapper\"><h4><span class=\"claim-number\">" + (jade.escape((jade_interp = claims[15].number) == null ? '' : jade_interp)) + "</span>Device</h4><p>" + (jade.escape((jade_interp = claims[15].text) == null ? '' : jade_interp)) + "</p><a class=\"expandable\"><span>17</span><span>20</span></a><div id=\"claim3\"><ul><li><span>17</span>" + (jade.escape((jade_interp = claims[16].text) == null ? '' : jade_interp)) + "</li><li><span>18</span>" + (jade.escape((jade_interp = claims[17].text) == null ? '' : jade_interp)) + "</li><li><span>19</span>" + (jade.escape((jade_interp = claims[18].text) == null ? '' : jade_interp)) + "</li><li><span>20</span>" + (jade.escape((jade_interp = claims[19].text) == null ? '' : jade_interp)) + "</li></ul></div><!-- /#claim--></div><!-- /.claim-wrapper-->");}("my_content" in locals_for_with?locals_for_with.my_content:typeof my_content!=="undefined"?my_content:undefined));;return buf.join("");
}